server:
  port: ${port:9400}
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom
  application:
    name: notification-service

logging:
  file:
    name: notification-service.log

gateway:
  public:
    ip: 3.16.180.134