server:
  port: ${port:9400}
spring:
  application:
    name: notification-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone:http: //localhost:8761/eureka
