server:
  port: ${port:9300}
spring:
  application:
    name: transaction-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom
api:
  transaction:
    actuator:
      url:
        path: /transaction/actuator/*
  zuul:
    actuator:
      url:
        path: /actuator/*

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

logging:
  level:
    com:
      jide:
        transactionservice:
          infrastructure:
            configurations:
              NotificationFeignClient: DEBUG