server:
  port: ${port:9500}
spring:
  application:
    name: transaction-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
api:
  transaction:
    actuator:
      url:
        path: /transaction/actuator/*
  zuul:
    actuator:
      url:
        path: /actuator/*

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

logging:
  level:
    com:
      jide:
        transactionservice:
          infrastructure:
            configurations:
              NotificationFeignClient: DEBUG
  file:
    name: transaction-service.log