server:
  port: ${port:9500}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  datasource:
    # Connection url for the database "fintech"
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:3307/fintechapp?createDatabaseIfNotExist=true&userSSL=false&serverTimezone=UTC}
    # Username and secret
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1007}
    initialization-mode: always
    dbcp2:
      # Keep the connection alive if idle for a long time (needed in production)
      test-while-idle: true
      validation-query: SELECT 1
    jpa:
      # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
      # stripped before adding them to the entity manager).

      # Show or not log for each sql query for debugging purposes. NB make sure to turn this off in production to avoid leaking some information
      hibernate:
        # Hibernate ddl auto (create, create-drop, update): with "update" the database
        # schema will be automatically updated accordingly to java entities found in
        # the project
        ddl-auto: update
      show-sql: true
  application:
    name: transaction-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
api:
  transaction:
    actuator:
      url:
        path: /actuator/*
    swagger:
      url:
        patha: /swagger-ui.html
        pathb: /swagger-resources/**
        pathc: /v2/api-docs
        pathd: /webjars/**
  zuul:
    actuator:
      url:
        path: /actuator/*

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

logging:
  level:
    com:
      jide:
        transactionservice:
          infrastructure:
            configurations:
              NotificationFeignClient: DEBUG
  file:
    name: transaction-service.log

secured:
  app:
    uri: /accounts/api/v1/auth/**
    header: Authorization
    prefix: Bearer
    jwtSecret: SecuredSecretKeyabracadabrajide05
    jwtExpirationMs: 86400000
myapplication:
  enviroment: development profile