server:
  port: ${port:9300}
spring:
  application:
    name: transaction-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom
api:
  transaction:
    actuator:
      url:
        path: /transaction/actuator/*
  zuul:
    actuator:
      url:
        path: /actuator/*