version: '3.6'
services:
  myapp:
    container_name: fintech-config-server
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - 9900:9600
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my_db:3306/mydb?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - my_db
    networks:
      - esnet
  my_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: fintechapp
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: pass
      # Password for root access
      MYSQL_ROOT_PASSWORD: pass
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - esnet
# Names our volume
volumes:
  my-db:
networks:
  esnet: