#FROM openjdk:13-jdk-alpine
#VOLUME /tmp

#COPY target/configserver-0.0.1-SNAPSHOT.jar ConfigServer.jar

#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","ConfigServer.jar"]


FROM fintech/configserver-builder:latest AS MAVEN_BUILD

COPY pom.xml /build/

WORKDIR /build/

COPY src /build/src/

ENV JAVA_OPTS=""

ENTRYPOINT mvn spring-boot:run -Dspring-boot.run.profiles=dev