server:
  port: 8765
spring:
  application:
    name: gateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom

secured:
  app:
    uri: /accounts/api/v1/auth/**
    header: Authorization
    prefix: Bearer
    jwtSecret: SecuredSecretKeyabracadabrajide05
    jwtExpirationMs: 86400000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}

zuul:
  host:
    time-to-live: -1
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
  routes:
    account-service:
      path: /accounts/**
      service-id: account-service
      sensitiveHeaders: Cookie,Set-Cookie
    transaction-service:
      path: /transaction/**
      service-id: transaction-service
      sensitiveHeaders: Cookie,Set-Cookie
    notification-service:
      path: /notification/**
      service-id: notification-service

  ignored-services: '*'

management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace


api:
  account:
    actuator:
      url:
        path: /accounts/actuator/*
    swagger:
      url:
        patha: /accounts/swagger-ui.html
        pathb: /accounts/swagger-resources/**
        pathc: /accounts/v2/api-docs
        pathd: /accounts/webjars/**

  transaction:
    actuator:
      url:
        path: /transaction/actuator/*
    swagger:
      url:
        patha: /transaction/swagger-ui.html
        pathb: /transaction/swagger-resources/**
        pathc: /transaction/v2/api-docs
        pathd: /transaction/webjars/**

  notification:
    actuator:
      url:
        path: /notification/actuator/*
    swagger:
      url:
        patha: /notification/swagger-ui.html
        pathb: /notification/swagger-resources/**
        pathc: /notification/v2/api-docs
        pathd: /notification/webjars/**
  zuul:
    actuator:
      url:
        path: /actuator/*
ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 122000


myapplication:
  enviroment: default profile