server:
  port: 8765
spring:
  application:
    name: gateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom




zuul:
  host:
    time-to-live: -1
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
  routes:
    account-service:
      path: /accounts/**
      service-id: account-service
      sensitiveHeaders: Cookie,Set-Cookie
    transaction-service:
      path: /transaction/**
      service-id: transaction-service
      sensitiveHeaders: Cookie,Set-Cookie
    notification-service:
      path: /notification/**
      service-id: notification-service

  ignored-services: '*'

management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace


api:
  account:
    actuator:
      url:
        path: /accounts/actuator/*
  zuul:
    actuator:
      url:
        path: /actuator/*
ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 122000
