server:
  port: 8765
spring:
  application:
    name: gateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom








zuul:

  routes:
    account-service:
      path: /accounts/**
      service-id: account-service

  ignored-services: '*'

management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace


api:
  account:
    actuator:
      url:
        path: /accounts/actuator/*
  zuul:
    actuator:
      url:
        path: /actuator/*

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
