#FROM openjdk:13-jdk-alpine
#VOLUME /tmp
#COPY target/transaction-service-0.0.1-SNAPSHOT.jar TransactionService.jar
#ENTRYPOINT ["java","-jar","TransactionService.jar"]

FROM fintech/transactionserver-builder:latest AS MAVEN_BUILD

COPY pom.xml /build/

WORKDIR /build/

COPY src /build/src/

ENV JAVA_OPTS=""

ENTRYPOINT mvn spring-boot:run -Dspring-boot.run.profiles=development