server:
  port: ${port:9200}
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom
  devtools:
    restart:
      enabled: true
  application:
    name: account-service
management:
  endpoints:
    web:
      exposure:
        include: mappings,health
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
logging:
  level:
    com:
      jide:
        accountservice:
          infrastructure:
            configurations:
              NotificationFeignClient: DEBUG



