server:
  port: ${port:9200}
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: freedom
  devtools:
    restart:
      enabled: true
  application:
    name: account-service




