#FROM openjdk:13-jdk-alpine
#VOLUME /tmp
#COPY target/gateway-service-0.0.1-SNAPSHOT.jar GatewayService.jar
#ENTRYPOINT ["java","-jar","GatewayService.jar"]

FROM fintech/gatewayserver-builder:latest AS MAVEN_BUILD

COPY pom.xml /build/

WORKDIR /build/

COPY src /build/src/

ENV JAVA_OPTS=""

ENTRYPOINT mvn spring-boot:run -Dspring-boot.run.profiles=development